//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VekhaNNApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RawMaterials
    {
        public int MaterialID { get; set; }
        public string MaterialName { get; set; }
        public Nullable<int> Quantity { get; set; }
    }
}
